name: docker release

on:
  push:
    tags:
      - "*.*.*"

env:
  DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}

permissions:
  contents: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # This step is not required
      # - uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: [linux/amd64, linux/arm64, darwin/amd64]
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE }}:${{ matrix.arch }}-${{ github.ref_name }}
